# Generated by Django 5.2.17 on 2026-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(help_text="Resume/candidate ID (e.g. 'res_001'). Plain field — no FK for now.", max_length=64)),
                ('recruiter_id', models.IntegerField(default=0, help_text='Plain int — wire to auth.User FK when auth is set up.')),
                ('feedback', models.CharField(choices=[('good_fit', 'Good Fit'), ('not_a_fit', 'Not a Fit')], max_length=12)),
                ('skill_snapshot', models.JSONField(default=list, help_text='List of matched skill names at feedback time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillWeightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=dict, help_text='Mapping of {skill_name: weight_multiplier}. Default 1.0 for unseen.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Weight Snapshot',
                'verbose_name_plural': 'Skill Weight Snapshots',
            },
        ),
    ]
